name: KVar
title: KVar | A blog for Software Engineers, Managers and Architects
description: KVar.dev is your Single source of Technology Blog on Software
  Design & Engineering. We don't just Teach, we Build Together.
tags:
  - blog
  - software
  - golang
  - python
  - go
  - webdevelopment
  - projects
show_hero: true
paginate: 25
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: admin@kvar.dev
disqus_username: kvar-dev
